#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=3

# Download, check integrity, uncompress and patch the source from app.src
#ynh_setup_source --dest_dir="$install_dir"

# Clone repo 
git clone --quiet $repo_url -b $repo_branch "$install_dir"

# Reset branch to the level of update we needed
pushd "$install_dir"
	git reset --hard --quiet $version_commit
popd

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring PHP-FPM..." --weight=3

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --usage=low --footprint=low

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# CONFIGURE RSS-BRIDGE
#=================================================
ynh_script_progression --message="Configuring RSS-Bridge..." --weight=1

# Enable every bridge
for i in $install_dir/bridges/*.php ; do 
  echo $(basename $i) | sed "s|Bridge.php$||g" | tee -a $install_dir/whitelist.txt
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
