#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# CHECK VERSION
#=================================================

upgrade_type=$(ynh_check_app_version_changed)

#=================================================
# STANDARD UPGRADE STEPS
#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression --message="Ensuring downward compatibility..." --weight=1

# If fpm_footprint doesn't exist, create it
if [ -z "${fpm_footprint:-}" ]; then
	fpm_footprint=low
	ynh_app_setting_set --app=$app --key=fpm_footprint --value=$fpm_footprint
fi

# If fpm_usage doesn't exist, create it
if [ -z "${fpm_usage:-}" ]; then
	fpm_usage=low
	ynh_app_setting_set --app=$app --key=fpm_usage --value=$fpm_usage
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

if [ "$upgrade_type" == "UPGRADE_APP" ]
then
	ynh_script_progression --message="Upgrading source files..." --weight=2

	# Download, check integrity, uncompress and patch the source from app.src
	#ynh_setup_source --dest_dir="$install_dir" --keep="whitelist.txt"

	pushd "$install_dir"
    if [ ! `git rev-parse --is-inside-work-tree &> /dev/null` ]; then
        # If current install is not a Git repo then init one
        git init --quiet
        if ! git config remote.origin.url > /dev/null; then
            # If remote does not exist, add it
            git remote add origin $repo_url
        fi
		git fetch origin --quiet
    	git checkout -b $repo_branch --track origin/$repo_branch --force --quiet
    fi
    git fetch --quiet
    git checkout $repo_branch --quiet
    git pull --quiet
    git reset --hard $version_commit --quiet
    popd
fi

chmod -R o-rwx "$install_dir"
chown -R $app:www-data "$install_dir"

#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Upgrading PHP-FPM configuration..." --weight=3

# Create a dedicated PHP-FPM config
ynh_add_fpm_config --phpversion=$phpversion --usage=$fpm_usage --footprint=$fpm_footprint

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC UPGRADE
#=================================================
# CONFIGURE RSS-BRIDGE
#=================================================
ynh_script_progression --message="Configuring RSS-Bridge..." --weight=2

# Enable every bridge
for i in $install_dir/bridges/*.php ; do 
  echo $(basename $i) | sed "s|Bridge.php$||g" | tee -a $install_dir/whitelist.txt
done

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Upgrade of $app completed" --last
